# Generated by Django 5.1.4 on 2025-01-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_borrowed", models.DateField(auto_now_add=True)),
                ("expected_return_date", models.DateField()),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Borrowed", "Borrowed"),
                            ("Returned", "Returned"),
                            ("Overdue Returned", "Overdue Returned"),
                            ("Overdue", "Overdue"),
                        ],
                        default="Borrowed",
                        max_length=17,
                    ),
                ),
                ("overdue_days", models.IntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="books.book"
                    ),
                ),
            ],
            options={
                "ordering": ["expected_return_date"],
            },
        ),
    ]
