# Generated by Django 5.1.4 on 2025-01-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_num",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
